# Generated by Django 5.1.3 on 2024-11-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.PositiveBigIntegerField(default=1859752549477777408, primary_key=True, serialize=False),
        ),
    ]
